Repository IvanVBBD/Crosses, pull requests merged in 2023-06, with the labels that each got.

#4 Hyla/gamepage game history
  resource/pages/game.html
  resource/pages/login.html
  resource/scripts/game.js
  resource/static/github-logo.png
  resource/static/greyscale_google_logo.png
  resource/styles/game.css
  resource/styles/login.css
  resource/styles/main.css
Labels: feature

#7 Added controller for db connections
  auth/controllers/dbControl.js
  resource/controllers/authControl.js
  resource/controllers/dbControl.js
  resource/index.js
  resource/routes/dataRoute.js
Labels: feature

#11 fixed play-again button and issue with tieing
  resource/pages/login.html
  resource/scripts/game.js
  resource/styles/game.css
Labels: bug

#13 fixed routing issue with css on history route and added profile page
  resource/index.js
  resource/pages/game.html
  resource/pages/history.html
  resource/pages/login.html
  resource/pages/profile.html
  resource/routes/gameRoute.js
  resource/routes/historyRoute.js
  resource/routes/profileRoute.js
  resource/scripts/game.js
  resource/scripts/history.js
  resource/scripts/profile.js
  resource/styles/game.css
  resource/styles/login.css
  resource/styles/main.css
  resource/styles/profile.css
Labels: bug, feature
